import { randomUUID } from "node:crypto";
import type { JsonSchema, McpServerInfo, McpServerStatus, ToolParam, ToolSpec } from "../../../shared/types";
import type { ToolRegistry } from "../registry";
import { clamp, fail, ok, type Tool } from "../types";
import { McpClient, type McpTool } from "./mcpClient";
import { McpStdioClient } from "./mcpStdioClient";
import type { IMcpClient } from "./transport";

export const MCP_PREFIX="mcp_";
export interface McpServerConfig{id:string;transport:"http"|"stdio";url?:string;headers?:Record<string,string>;command?:string;args?:string[];env?:Record<string,string>;}
interface Entry{config:McpServerConfig;client?:IMcpClient;status:McpServerStatus;toolCount:number;message?:string;}
export class McpManager{
  private readonly entries=new Map<string,Entry>();
  constructor(private readonly registry:ToolRegistry,private readonly log:(msg:string)=>void){}
  async setConfigs(configs:McpServerConfig[]):Promise<void>{for(const id of [...this.entries.keys()])if(!configs.some(c=>c.id===id)){await this.disconnect(id);this.entries.delete(id);}for(const c of configs){const e=this.entries.get(c.id);if(e)e.config=c;else this.entries.set(c.id,{config:c,status:"pending",toolCount:0});}}
  async connect(id:string):Promise<void>{const e=this.entries.get(id);if(!e)return;await this.teardownClient(e);e.status="approved";let client:IMcpClient;try{client=createClient(e.config);}catch(err){e.status="error";e.message=(err as Error).message;this.log(`MCP "${id}": ${e.message}`);return;}try{await client.connect();const tools=await client.listTools();this.registry.unregisterByPrefix(prefixFor(id));for(const t of tools)this.registry.register(makeBridgedTool(id,client,t));e.client=client;e.status="connected";e.toolCount=tools.length;e.message=undefined;this.log(`MCP "${id}": connected, ${tools.length} tool(s).`);}catch(err){await client.close().catch(()=>undefined);e.status="error";e.toolCount=0;e.message=(err as Error).message;this.log(`MCP "${id}": ${e.message}`);}}
  async disconnect(id:string,status:McpServerStatus="revoked"):Promise<void>{const e=this.entries.get(id);if(!e)return;this.registry.unregisterByPrefix(prefixFor(id));await this.teardownClient(e);e.toolCount=0;e.status=status;}
  list():McpServerInfo[]{return[...this.entries.values()].map(e=>({id:e.config.id,transport:e.config.transport,target:e.config.transport==="http"?e.config.url??"":mkCmd(e.config),status:e.status,toolCount:e.toolCount,message:e.message}));}
  async dispose():Promise<void>{for(const id of this.entries.keys())this.registry.unregisterByPrefix(prefixFor(id));await Promise.all([...this.entries.values()].map(e=>e.client?.close().catch(()=>undefined)));this.entries.clear();}
  private async teardownClient(e:Entry):Promise<void>{if(e.client){await e.client.close().catch(()=>undefined);e.client=undefined;}}
}
const ALLOWED_STDIO_BINS=new Set(["npx","node","python","python3","uvx","bun","deno"]);const BLOCKED_ARG_RE=/(^|\s)(rm\s+-rf|sudo|chmod\s+\+x|\|\s*sh|;\s*)/i;
function createClient(c:McpServerConfig):IMcpClient{if(c.transport==="stdio"){if(!c.command)throw new Error("stdio MCP server requires a `command`.");const bin=c.command.split(/[\\/]/).pop()?.split(/\s+/)[0]?.toLowerCase()??"";if(!ALLOWED_STDIO_BINS.has(bin)&&!c.command.startsWith("node "))throw new Error(`Blocked stdio command "${c.command}" — executable is not allowlisted.`);if(BLOCKED_ARG_RE.test((c.args??[]).join(" ")))throw new Error("Blocked suspicious MCP args (shell injection pattern).");const safeEnv:Record<string,string>|undefined=c.env?Object.fromEntries(Object.entries(c.env).filter(([k])=>/^(PATH|NODE_ENV|PYTHONPATH)$/i.test(k)||k.startsWith("MCP_"))):undefined;return new McpStdioClient(c.command,c.args??[],safeEnv);}if(!c.url)throw new Error("http MCP server requires a `url`.");if(!/^https:\/\//i.test(c.url))throw new Error(`Blocked MCP url "${c.url}" — use an HTTPS endpoint.`);if(!isSafeRemoteUrl(c.url))throw new Error("Blocked MCP URL targeting a local/private network address.");return new McpClient(c.url,c.headers);}
function isSafeRemoteUrl(raw:string):boolean{let u:URL;try{u=new URL(raw);}catch{return false;}const h=u.hostname.toLowerCase();if(u.protocol!=="https:")return false;if(h==="localhost"||h.endsWith(".local")||h==="127.0.0.1"||h==="::1"||h==="0.0.0.0")return false;if(/^10\./.test(h)||/^192\.168\./.test(h)||/^172\.(1[6-9]|2\d|3[0-1])\./.test(h)||/^169\.254\./.test(h))return false;return true;}
function mkCmd(c:McpServerConfig):string{return[c.command??"",...(c.args??[])].join(" ").trim();}function prefixFor(serverId:string):string{return`${MCP_PREFIX}${serverId}_`.replace(/[^a-z0-9_]/gi,"_");}
function makeBridgedTool(serverId:string,client:IMcpClient,mcp:McpTool):Tool{const risk=inferRisk(mcp);const readOnly=risk==="read";const rawSchema=mcp.inputSchema as any;const schema:JsonSchema=rawSchema as JsonSchema;const spec:ToolSpec={name:`${MCP_PREFIX}${serverId}_${mcp.name}`.replace(/[^a-z0-9_]/gi,"_"),summary:mcp.description?.split("\n")[0]?.slice(0,160)??`MCP tool ${mcp.name}`,params:flattenSchema(schema),inputSchema:schema,sideEffecting:!readOnly,priority:readOnly?9:15,minTier:"medium",tags:["mcp",readOnly?"read":"write"],risk,concurrency:readOnly?"safe_parallel":"serial",idempotency:readOnly?"idempotent":"stateful"};return{spec,async execute(args,ctx){if(!readOnly){const approved=await ctx.requestApproval({id:randomUUID(),name:spec.name,args,status:"proposed",sideEffecting:true});if(!approved)return fail("User declined the MCP tool call.");}try{return ok(clamp(await client.callTool(mcp.name,args),6000));}catch(e){return fail(`MCP tool "${mcp.name}" failed: ${(e as Error).message}`,{retryable:true,recovery:{action:"retry"}});}}};}
function inferRisk(mcp:McpTool):"read"|"workspace_write"|"execute"|"network"|"destructive"{const text=`${mcp.name} ${mcp.description??""}`.toLowerCase();if(/\b(delete|destroy|drop|purge|wipe|reset|remove)\b/.test(text))return"destructive";if(/\b(execute|shell|command|terminal|run)\b/.test(text))return"execute";if(/\b(fetch|http|request|search|browser|web)\b/.test(text))return"network";if(/\b(write|edit|update|create|insert|move|rename|save|patch)\b/.test(text))return"workspace_write";return"read";}
function flattenSchema(schema:JsonSchema):ToolParam[]{const properties=schema.properties??{};const required=new Set(schema.required??[]);return Object.entries(properties).map(([name,def])=>({name,type:mapType(def.type),required:required.has(name),description:def.description??"",...(Array.isArray(def.enum)?{enum:def.enum}:{}),...(def.items?{items:def.items}:{}) ,...(def.properties?{properties:def.properties}:{})}));}
function mapType(t?:string):ToolParam["type"]{if(t==="number"||t==="integer"||t==="boolean")return t as ToolParam["type"];return"string";}
