import type { AdaptivePlan, AutoDecision, BenchResult, ComplexityAssessment, MachineProfile, Mode, ModelInfo, ModelScore } from "../../shared/types";
import { capabilityForModel, analyzeTask, toComplexity } from "../intelligence/policy";
import { buildPlan, type OrchestratorInput } from "./orchestrator";
import { estimateTokens } from "./tokens";
const WEIGHTS={contextFit:30,contextHeadroom:6,throughput:12,toolCalling:18,reasoning:12,coding:14,recovery:10,verification:8,tierMatch:8,localPreference:3};
export interface AutoModeInput{prompt:string;mode:Mode;attachmentCount?:number;models:ModelInfo[];machine:MachineProfile|null;benchByModel?:Map<string,BenchResult>;pinnedModel?:string;}
export function rankModels(models:ModelInfo[],complexity:ComplexityAssessment,benchByModel?:Map<string,BenchResult>):ModelScore[]{const task=complexity.task??analyzeTask("", "agent");const tpsValues=[...(benchByModel?.values()??[])].map(b=>b.tokensPerSec).filter(v=>v>0);const maxTps=Math.max(...tpsValues,1);const idealReasoning=task.reasoning==="high"?.85:task.reasoning==="medium"?.65:.45;const idealTool=task.scope==="single_file"&&task.verification.length===0?.55:.75;return models.map(m=>{const bench=benchByModel?.get(m.name);const caps=capabilityForModel(m,bench);const ctx=m.contextLength??8192;const fits=ctx>=complexity.minContextTokens;let score=0;const reasons:string[]=[];if(fits){score+=WEIGHTS.contextFit;score+=Math.min(1,(ctx-complexity.minContextTokens)/Math.max(1,complexity.minContextTokens))*WEIGHTS.contextHeadroom;reasons.push(`context ${ctx.toLocaleString()} fits`);}else{reasons.push(`context ${ctx.toLocaleString()} is tight`);score-=WEIGHTS.contextFit*.75;}score+=caps.toolCalling*WEIGHTS.toolCalling;score+=caps.coding*WEIGHTS.coding;score+=caps.recovery*WEIGHTS.recovery;score+=caps.verification*WEIGHTS.verification;score+=Math.max(0,1-Math.abs(caps.reasoning-idealReasoning))*WEIGHTS.reasoning;score+=Math.max(0,1-Math.abs(caps.toolCalling-idealTool))*WEIGHTS.tierMatch;reasons.push(`tool ${Math.round(caps.toolCalling*100)}%`);reasons.push(`coding ${Math.round(caps.coding*100)}%`);if(task.reasoning!=="low")reasons.push(`reasoning ${Math.round(caps.reasoning*100)}%`);if(bench&&maxTps>0){score+=(bench.tokensPerSec/maxTps)*WEIGHTS.throughput;reasons.push(`${Math.round(bench.tokensPerSec)} tok/s`);}if(m.provider==="ollama"||m.provider==="llamacpp"){score+=WEIGHTS.localPreference;reasons.push("local");}if(bench?.capabilityProfile)reasons.push("bench-profiled");return{model:m.name,score:Math.round(score*100)/100,fits,reasons};}).sort((a,b)=>b.score-a.score);}
export function decideModel(input:AutoModeInput):AutoDecision{const promptTokens=estimateTokens(input.prompt??"");const task=analyzeTask(input.prompt,input.mode,input.attachmentCount??0);const complexity=toComplexity(task,promptTokens);const scores=rankModels(input.models,complexity,input.benchByModel);const pinnedExists=!!input.pinnedModel&&input.models.some(m=>m.name===input.pinnedModel);if(pinnedExists)return{chosenModel:input.pinnedModel!,auto:false,pinned:true,complexity,scores,reason:`Pinned to ${input.pinnedModel}.`};const best=scores[0];if(!best)return{chosenModel:"",auto:true,pinned:false,complexity,scores,reason:"No models available."};return{chosenModel:best.model,auto:true,pinned:false,complexity,scores,reason:`${best.model} selected for ${task.scope}/${task.reasoning} work; ${best.reasons.slice(0,3).join(", ")}.`};}
export interface PlanRequest extends AutoModeInput{intelligence:OrchestratorInput["intelligence"];reserveOutputTokens:number;adaptiveEnabled:boolean;userNumCtx?:number;cloudNativeTools?:boolean;}
export function planRequest(input:PlanRequest):{decision:AutoDecision;plan:AdaptivePlan|null}{const decision=decideModel(input);const model=input.models.find(m=>m.name===decision.chosenModel);if(!model)return{decision,plan:null};const plan=buildPlan({model,machine:input.machine,mode:input.mode,prompt:input.prompt,userNumCtx:input.userNumCtx,intelligence:input.intelligence,reserveOutputTokens:input.reserveOutputTokens,adaptiveEnabled:input.adaptiveEnabled,cloudNativeTools:input.cloudNativeTools,task:decision.complexity.task,bench:input.benchByModel?.get(model.name)});return{decision,plan};}
